import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
process.chdir(root);
const rawPlugin={name:'raw',setup(b){b.onResolve({filter:/\?raw$/},a=>({path:resolve(a.resolveDir,a.path.slice(0,-4)),namespace:'raw'}));b.onLoad({filter:/.*/,namespace:'raw'},async a=>({contents:await readFile(a.path,'utf8'),loader:'text'}));}};
const worker=await build({entryPoints:['web/workers/prediction.worker.js'],bundle:true,write:false,format:'iife',target:'chrome109',plugins:[rawPlugin]});
const workerSource=worker.outputFiles[0].text;
const workerPlugin={name:'worker',setup(b){b.onResolve({filter:/^prediction-worker-source$/},()=>({path:'worker',namespace:'worker'}));b.onLoad({filter:/.*/,namespace:'worker'},()=>({contents:workerSource,loader:'text'}));}};
const page=await build({entryPoints:['web/main.js'],bundle:true,write:false,format:'esm',target:'chrome109',minify:true,plugins:[rawPlugin,workerPlugin]});
const template=await readFile('web/index.html','utf8');
const script=page.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
const hash=createHash('sha256').update(script).digest('base64');
const html=template.replace('__STYLES__',await readFile('web/styles.css','utf8')).replace('<script>__SCRIPT__</script>',()=>'<script type="module">'+page.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+'</script>');
const pkg=JSON.parse(await readFile('package.json','utf8'));
const secured=html.replace("script-src 'self' 'unsafe-inline' blob:",`script-src 'sha256-${hash}'`);
await mkdir('dist',{recursive:true});
const output=`dist/Promoter-Calculator-Desktop-v${pkg.version}.html`;
await writeFile(output,secured);
console.log(`Built ${resolve(output)} (${(Buffer.byteLength(secured)/1024/1024).toFixed(1)} MB).`);
